<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MasterMobil extends Model
{
    use HasFactory;
    protected $fillable = [
        'nama',
        'tahun',
        'keterangan',
        'image',
        'no_pol',
        'status'
    ];

    public function harga(){
        return $this->hasMany(MasterHarga::class,'mobil_id');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($harga){
            $harga->harga()->delete();
        });
    }
}
